import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { FileUp, Loader2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { createPartnerInvoice, getPartnerWorkspace, updateServiceRequest } from "@/lib/service-partners.functions";

export const Route = createFileRoute("/partner/")({ head: () => ({ meta: [{ title: "طلبات الشركة | بوابة شريك الرشودي" }, { name: "description", content: "طلبات عملاء الرشودي الموجهة إلى شركة الخدمات وفواتيرها." }, { property: "og:title", content: "طلبات الشركة | بوابة شريك الرشودي" }, { property: "og:description", content: "إدارة طلبات العملاء وإصدار فواتير الخدمات." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }, { name: "robots", content: "noindex" }] }), component: PartnerHome });

function PartnerHome() {
  const qc = useQueryClient();
  const workspace = useQuery({ queryKey: ["partner-workspace"], queryFn: () => getPartnerWorkspace() });
  const [invoiceFor, setInvoiceFor] = useState<string | null>(null);
  const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [file, setFile] = useState<File | null>(null);
  const refresh = () => qc.invalidateQueries({ queryKey: ["partner-workspace"] });
  const status = useMutation({ mutationFn: (input: { requestId: string; status: string }) => updateServiceRequest({ data: input }), onSuccess: () => { void refresh(); toast.success("تم تحديث الطلب"); } });
  const invoice = useMutation({ mutationFn: async () => { if (!invoiceFor) throw new Error("اختر الطلب"); const partnerId = workspace.data?.partner.id; if (!partnerId) throw new Error("الحساب غير مرتبط"); let imagePath: string | undefined; if (file) { imagePath = `${partnerId}/${invoiceFor}/${Date.now()}-${file.name.replace(/[^\w.-]/g, "_")}`; const up = await supabase.storage.from("service-partartner-files").upload(imagePath, file); if (up.error) throw up.error; } return createPartnerInvoice({ data: { requestId: invoiceFor, ...(amount ? { amount: Number(amount) } : {}), ...(description.trim() ? { description: description.trim() } : {}), ...(imagePath ? { imagePath } : {}) } }); }, onSuccess: () => { setInvoiceFor(null); setAmount(""); setDescription(""); setFile(null); void refresh(); toast.success("تم إصدار الفاتورة للعميل"); }, onError: (e) => toast.error(e instanceof Error ? e.message : "تعذّر إصدار الفاتورة") });
  if (workspace.isLoading) return <Loader2 className="size-6 animate-spin text-primary" />;
  if (workspace.error) return <p className="text-destructive">{(workspace.error as Error).message}</p>;
  const data = workspace.data;
  if (!data) return null;
  return <div className="space-y-7"><header><h1 className="text-2xl font-black">{data.partner.name}</h1><p className="text-sm text-muted-foreground">طلبات العملاء والفواتير الخاصة بمؤسستكم فقط.</p></header><section className="space-y-3"><h2 className="text-lg font-bold">الطلبات</h2>{data.requests.map((r) => <article key={r.id} className="rounded-xl border border-border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{r.request_number} — {r.customer_name}</p><p dir="ltr" className="mt-1 text-end text-sm text-muted-foreground">{r.customer_phone}</p></div><select className="h-10 rounded-lg border border-border bg-background px-3 text-sm" value={r.status} onChange={(e) => status.mutate({ requestId: r.id, status: e.target.value })}><option value="new">جديد</option><option value="accepted">مقبول</option><option value="in_progress">قيد التنفيذ</option><option value="completed">مكتمل</option><option value="cancelled">ملغي</option></select></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><p><b>الخدمة:</b> {r.service_type}</p><p><b>العنوان:</b> {r.address}</p><p><b>الهوية:</b> {r.customer_identity ?? "—"}</p></div><p className="mt-3 rounded-lg bg-muted p-3 text-sm">{r.details}</p><Button className="mt-4" variant="outline" onClick={() => setInvoiceFor(r.id)}><FileUp className="size-4" /> إصدار فاتورة</Button></article>)}</section>{invoiceFor ? <section className="rounded-xl border border-primary/30 bg-card p-5"><h2 className="font-bold">فاتورة جديدة</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm">المبلغ (اختياري)<input type="number" className="mt-1 h-11 w-full rounded-lg border border-border bg-background px-3" value={amount} onChange={(e) => setAmount(e.target.value)} /></label><label className="text-sm">صورة أو ملف الفاتورة (اختياري)<input type="file" accept="image/*,.pdf" className="mt-1 block w-full text-sm" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></label><label className="text-sm sm:col-span-2">تفاصيل الفاتورة<textarea className="mt-1 min-h-24 w-full rounded-lg border border-border bg-background p-3" value={description} onChange={(e) => setDescription(e.target.value)} /></label></div><div className="mt-4 flex gap-2"><Button onClick={() => invoice.mutate()} disabled={invoice.isPending}>إصدار وإرسال للعميل</Button><Button variant="ghost" onClick={() => setInvoiceFor(null)}>إلغاء</Button></div></section> : null}<section id="invoices" className="space-y-3"><h2 className="text-lg font-bold">الفواتير</h2>{data.invoices.map((i) => <article key={i.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card p-4"><p className="font-bold">{i.invoice_number}</p><p>{i.amount == null ? "المبلغ في المرفق" : `${Number(i.amount).toLocaleString("ar-SA")} ر.س`}</p><span className="rounded-full bg-primary/10 px-3 py-1 text-xs text-primary">صادرة</span></article>)}</section></div>;
}
