import { useQuery } from "@tanstack/react-query";
import { BarChart3, BrainCircuit, Building2, CalendarClock, CircleDollarSign, Clock3, MapPinned, Settings2, ShieldAlert, TrendingUp, Users, Wrench } from "lucide-react";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { formatCurrency } from "@/components/kit/LiveTable";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { cn } from "@/lib/utils";

type Tab = "money" | "portfolio" | "crm" | "operations" | "smart";
type Payment = { contract_id: string; amount_due: number; amount_paid: number; due_date: string; status: string };
type Contract = { id: string; contract_number: string; property_id: string | null; unit_id: string | null; tenant_id: string | null; start_date: string | null; end_date: string | null; created_at: string; status: string; total_value: number | null; annual_rent: number | null; previous_contract_id: string | null };
type Property = { id: string; name: string; city: string | null; district: string | null; latitude: number | null; longitude: number | null; status: string };
type Expense = { amount: number; category: string; spent_on: string; property_id: string | null };
type Opportunity = { stage: string; expected_value: number | null; contact_id: string | null; assigned_to: string | null };
type Task = { id: string; status: string; task_type: string; created_at: string; started_at: string | null; submitted_at: string | null; approved_at: string | null; due_date: string | null; property_id: string | null };
type Assignment = { task_id: string; user_id: string; profile: { full_name: string } | null };
type InsightMetrics = ReturnType<typeof calculateMetrics>;

const panels: Record<string, string> = { cash:"توقع التدفق النقدي", aging:"أعمار المتأخرات", expiry:"خريطة انتهاء العقود", occupancy:"اتجاه الإشغال", vacancy:"متوسط أيام الشغور", profit:"ربحية كل عقار", ranking:"ترتيب العقارات", risk:"مخاطر العقود", forecast:"توقع التحصيل", retention:"الاحتفاظ بالمستأجرين", pipeline:"مسار الفرص", sources:"مصادر العملاء", response:"سرعة الاستجابة", team:"أداء الفريق", maintenance:"الصيانة", geo:"التوزيع الجغرافي", comparison:"مقارنة الفترات", customize:"منشئ اللوحة", simulator:"محاكي السيناريوهات", summary:"الموجز التنفيذي" };
const allPanels = Object.keys(panels);
const tabItems: { key: Tab; label: string }[] = [{key:"money",label:"المالية"},{key:"portfolio",label:"المحفظة"},{key:"crm",label:"العملاء والفريق"},{key:"operations",label:"المخاطر والصيانة"},{key:"smart",label:"التحليل المتقدم"}];
const sum = (items: number[]) => items.reduce((a,b) => a+b, 0);
const days = (a: string, b: string) => Math.max(0, Math.round((new Date(b).getTime()-new Date(a).getTime())/86400000));
const monthKey = (date: Date) => date.toISOString().slice(0,7);
const monthLabel = (key: string) => new Intl.DateTimeFormat("ar-SA", { month:"short" }).format(new Date(`${key}-01T12:00:00`));
const change = (a:number,b:number) => b ? Math.round((a-b)/b*100) : a ? 100 : 0;

function calculateMetrics(data: { payments: Payment[]; contracts: Contract[]; units: { id:string; created_at:string }[]; properties: Property[]; expenses: Expense[]; opportunities: Opportunity[]; contacts: {id:string;source:string|null}[]; tasks: Task[]; assignments: Assignment[]; requests: {created_at:string;updated_at:string}[] }) {
  const now=new Date(), today=now.toISOString().slice(0,10), propertyMap=new Map(data.properties.map(p=>[p.id,p])), contactSource=new Map(data.contacts.map(c=>[c.id,c.source||"غير محدد"]));
  const cash=[30,60,90].map(n=>{const end=new Date(now.getTime()+n*86400000).toISOString().slice(0,10), rows=data.payments.filter(p=>p.due_date>=today&&p.due_date<=end); return {label:`${n} يوم`, expected:sum(rows.map(p=>Math.max(0,p.amount_due-p.amount_paid))), paid:sum(rows.map(p=>p.amount_paid))};});
  const aging=[{label:"1–30",a:1,b:30},{label:"31–60",a:31,b:60},{label:"61–90",a:61,b:90},{label:"+90",a:91,b:99999}].map(x=>({...x,value:sum(data.payments.filter(p=>p.status!=="paid"&&p.due_date<today&&days(p.due_date,today)>=x.a&&days(p.due_date,today)<=x.b).map(p=>Math.max(0,p.amount_due-p.amount_paid)))}));
  const keys=Array.from({length:12},(_,i)=>monthKey(new Date(now.getFullYear(),now.getMonth()-5+i,1)));
  const expiry=keys.slice(6).map(k=>({label:monthLabel(k),count:data.contracts.filter(c=>c.end_date?.startsWith(k)).length}));
  const occupancy=keys.slice(0,6).map(k=>{const end=new Date(`${k}-01T12:00:00`);end.setMonth(end.getMonth()+1);end.setDate(0);const total=data.units.filter(u=>new Date(u.created_at)<=end).length, occupied=new Set(data.contracts.filter(c=>c.unit_id&&c.start_date&&new Date(c.start_date)<=end&&(!c.end_date||new Date(c.end_date)>=new Date(`${k}-01`))).map(c=>c.unit_id)).size;return {label:monthLabel(k),value:total?Math.min(100,Math.round(occupied/total*100)):0};});
  const byUnit=new Map<string,Contract[]>(); data.contracts.forEach(c=>{if(c.unit_id)byUnit.set(c.unit_id,[...(byUnit.get(c.unit_id)||[]),c])}); const gaps:number[]=[]; byUnit.forEach(rows=>rows.sort((a,b)=>(a.start_date||"").localeCompare(b.start_date||"")).forEach((c,i)=>{const p=rows[i-1];if(i&&p?.end_date&&c.start_date)gaps.push(days(p.end_date,c.start_date))}));
  const stats=new Map(data.properties.map(p=>[p.id,{name:p.name,paid:0,due:0,cost:0,contracts:0}])); data.contracts.forEach(c=>{if(!c.property_id)return;const s=stats.get(c.property_id);if(!s)return;s.contracts++;data.payments.filter(p=>p.contract_id===c.id).forEach(p=>{s.paid+=p.amount_paid;s.due+=p.amount_due})}); data.expenses.forEach(e=>{if(e.property_id){const s=stats.get(e.property_id);if(s)s.cost+=e.amount}}); const ranking=[...stats.values()].map(s=>({...s,net:s.paid-s.cost,rate:s.due?Math.round(s.paid/s.due*100):0})).sort((a,b)=>b.net-a.net);
  const late=new Map<string,number>();data.payments.filter(p=>p.status!=="paid"&&p.due_date<today).forEach(p=>late.set(p.contract_id,(late.get(p.contract_id)||0)+1)); const risks=data.contracts.map(c=>{const until=c.end_date?days(today,c.end_date):999, missing=[c.start_date,c.end_date,c.tenant_id,c.property_id].filter(v=>!v).length, overdue=late.get(c.id)||0;return {label:c.contract_number||"بدون رقم",overdue,score:Math.min(100,overdue*20+missing*12+(until<=30?25:until<=60?10:0))}}).filter(r=>r.score).sort((a,b)=>b.score-a.score);
  const tenants=new Set(data.contracts.map(c=>c.tenant_id).filter(Boolean)), renewed=new Set(data.contracts.filter(c=>c.previous_contract_id).map(c=>c.tenant_id).filter(Boolean));
  const stages=[['new','جديد'],['qualified','مؤهل'],['viewing','معاينة'],['negotiation','تفاوض'],['contract','تعاقد'],['won','ناجحة']] as const; const pipeline=stages.map(([key,label])=>({label,count:data.opportunities.filter(o=>o.stage===key).length}));
  const sourceMap=new Map<string,{count:number,value:number}>();data.opportunities.forEach(o=>{const source=o.contact_id?(contactSource.get(o.contact_id)||"غير محدد"):"غير محدد", x=sourceMap.get(source)||{count:0,value:0};x.count++;x.value+=Number(o.expected_value||0);sourceMap.set(source,x)});const sources=[...sourceMap].map(([label,x])=>({label,...x})).sort((a,b)=>b.value-a.value);
  const responseHours=data.requests.filter(r=>r.created_at!==r.updated_at).map(r=>(new Date(r.updated_at).getTime()-new Date(r.created_at).getTime())/3600000); const taskMap=new Map(data.tasks.map(t=>[t.id,t])), teamMap=new Map<string,{name:string,total:number,done:number,prompt:number[]}>();data.assignments.forEach(a=>{const t=taskMap.get(a.task_id);if(!t)return;const x=teamMap.get(a.user_id)||{name:a.profile?.full_name||"موظف",total:0,done:0,prompt:[]};x.total++;if(["approved","completed"].includes(t.status))x.done++;if(t.started_at)x.prompt.push((new Date(t.started_at).getTime()-new Date(t.created_at).getTime())/3600000);teamMap.set(a.user_id,x)});const team=[...teamMap.values()].map(x=>({...x,rate:x.total?Math.round(x.done/x.total*100):0,hours:x.prompt.length?Math.round(sum(x.prompt)/x.prompt.length):0})).sort((a,b)=>b.rate-a.rate);
  const maintenanceExpenses=data.expenses.filter(e=>/صيانة|maintenance/i.test(e.category)), maintenanceTasks=data.tasks.filter(t=>/صيانة|maintenance/i.test(t.task_type)), maintMap=new Map<string,number>();maintenanceExpenses.forEach(e=>{if(e.property_id)maintMap.set(e.property_id,(maintMap.get(e.property_id)||0)+e.amount)});const maintenance=[...maintMap].map(([id,value])=>({label:propertyMap.get(id)?.name||"عقار غير محدد",value})).sort((a,b)=>b.value-a.value);
  const geoMap=new Map<string,number>();data.properties.forEach(p=>{const key=[p.city,p.district].filter(Boolean).join("، ")||"غير محدد";geoMap.set(key,(geoMap.get(key)||0)+1)});const geo=[...geoMap].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value);
  const currentKey=monthKey(now), previousKey=monthKey(new Date(now.getFullYear(),now.getMonth()-1,1)), paid=(k:string)=>sum(data.payments.filter(p=>p.due_date.startsWith(k)).map(p=>p.amount_paid)), costs=(k:string)=>sum(data.expenses.filter(e=>e.spent_on.startsWith(k)).map(e=>e.amount));
  const historical=data.payments.filter(p=>p.due_date<today), historicalDue=sum(historical.map(p=>p.amount_due)), historicalPaid=sum(historical.map(p=>p.amount_paid)), open=sum(data.payments.filter(p=>p.status!=="paid").map(p=>Math.max(0,p.amount_due-p.amount_paid))), annualRent=sum(data.contracts.filter(c=>c.status==="active").map(c=>Number(c.annual_rent||c.total_value||0))), annualCosts=sum(data.expenses.filter(e=>new Date(e.spent_on)>=new Date(now.getFullYear()-1,now.getMonth(),now.getDate())).map(e=>e.amount));
  return {cash,aging,expiry,occupancy,vacancy:gaps.length?Math.round(sum(gaps)/gaps.length):0,ranking,risks,retention:tenants.size?Math.round(renewed.size/tenants.size*100):0,pipeline,sources,response:responseHours.length?Math.round(sum(responseHours)/responseHours.length*10)/10:0,team,maintenanceExpenses,maintenanceTasks,maintenance,geo,current:{paid:paid(currentKey),costs:costs(currentKey),contracts:data.contracts.filter(c=>c.created_at.startsWith(currentKey)).length},previous:{paid:paid(previousKey),costs:costs(previousKey),contracts:data.contracts.filter(c=>c.created_at.startsWith(previousKey)).length},probability:historicalDue?Math.min(100,Math.round(historicalPaid/historicalDue*100)):0,open,annualRent,annualCosts};
}

export function DashboardInsights(){
 const [tab,setTab]=useState<Tab>("money"),[settings,setSettings]=useState(false),[visible,setVisible]=useState(allPanels),[rent,setRent]=useState(5),[occupancy,setOccupancy]=useState(0),[costs,setCosts]=useState(0);
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem("rashoudi_dashboard_panels")||"null");if(Array.isArray(v))setVisible(v)}catch{localStorage.removeItem("rashoudi_dashboard_panels")}},[]);
 const query=useQuery({queryKey:["dashboard-insights-v2"],staleTime:60000,queryFn:async()=>{const r=await Promise.all([supabase.from("contract_payments").select("contract_id, amount_due, amount_paid, due_date, status"),supabase.from("contracts").select("id, contract_number, property_id, unit_id, tenant_id, start_date, end_date, created_at, status, total_value, annual_rent, previous_contract_id"),supabase.from("units").select("id, created_at"),supabase.from("properties").select("id, name, city, district, latitude, longitude, status"),supabase.from("unit_expenses").select("amount, category, spent_on, property_id"),supabase.from("opportunities").select("stage, expected_value, contact_id, assigned_to"),supabase.from("contacts").select("id, source"),supabase.from("tasks").select("id, status, task_type, created_at, started_at, submitted_at, approved_at, due_date, property_id"),supabase.from("task_assignees").select("task_id, user_id, profile:user_id(full_name)"),supabase.from("supply_requests").select("created_at, updated_at"),supabase.from("listing_requests").select("created_at, updated_at")]);const failed=r.find(x=>x.error);if(failed?.error)throw failed.error;return {payments:(r[0].data||[]) as Payment[],contracts:(r[1].data||[]) as Contract[],units:(r[2].data||[]) as {id:string;created_at:string}[],properties:(r[3].data||[]) as Property[],expenses:(r[4].data||[]) as Expense[],opportunities:(r[5].data||[]) as Opportunity[],contacts:(r[6].data||[]) as {id:string;source:string|null}[],tasks:(r[7].data||[]) as Task[],assignments:(r[8].data||[]) as unknown as Assignment[],requests:[...(r[9].data||[]),...(r[10].data||[])] as {created_at:string;updated_at:string}[]}}});
 const m=useMemo(()=>query.data?calculateMetrics(query.data):null,[query.data]); const shown=(k:string)=>visible.includes(k), toggle=(k:string)=>{const v=shown(k)?visible.filter(x=>x!==k):[...visible,k];setVisible(v);localStorage.setItem("rashoudi_dashboard_panels",JSON.stringify(v))};
 if(query.isLoading)return <div className="surface-card p-10 text-center text-sm text-muted-foreground">جاري إعداد التحليلات المتقدمة…</div>;if(!m)return <div className="surface-card p-8 text-center text-sm text-destructive">تعذّر تحميل التحليلات المتقدمة.</div>;
 const projected=Math.max(0,m.annualRent*(1+rent/100)*(1+occupancy/100)-m.annualCosts*(1+costs/100)), currentNet=m.annualRent-m.annualCosts;
 return <section className="space-y-4"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold text-primary">مركز التحليلات</p><h2 className="mt-1 text-lg font-bold">رؤية تشغيلية متكاملة</h2><p className="mt-1 text-xs text-muted-foreground">20 مؤشرًا محسوبة من بيانات النظام الحالية.</p></div><Button variant="outline" size="sm" onClick={()=>setSettings(!settings)}><Settings2/>تخصيص اللوحة</Button></header>
 {settings&&<div className="surface-card p-4"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(panels).map(([k,v])=><label key={k} className="flex cursor-pointer items-center gap-2 rounded-md border border-border p-2 text-xs"><input type="checkbox" checked={shown(k)} onChange={()=>toggle(k)} className="accent-primary"/>{v}</label>)}</div></div>}
 <div className="flex gap-1 overflow-x-auto border-b border-border" role="tablist">{tabItems.map(t=><Button key={t.key} role="tab" aria-selected={tab===t.key} variant="ghost" onClick={()=>setTab(t.key)} className={cn("shrink-0 rounded-b-none border-b-2",tab===t.key?"border-primary text-primary":"border-transparent text-muted-foreground")}>{t.label}</Button>)}</div>
 {tab==="money"&&<Grid>{shown("cash")&&<Panel title="توقع التدفق النقدي" sub="المبالغ المنتظر تحصيلها تراكميًا" icon={CircleDollarSign}><Bars data={m.cash} x="label" series={[['expected','متوقع','var(--color-primary)'],['paid','محصل','var(--color-success)']]} currency/></Panel>}{shown("aging")&&<Panel title="أعمار المتأخرات" sub="الرصيد حسب مدة التأخر" icon={Clock3}><Bars data={m.aging} x="label" series={[['value','متأخر','var(--color-destructive)']]} currency/></Panel>}{shown("profit")&&<Panel title="ربحية كل عقار" sub="المحصّل ناقص المصروفات" icon={TrendingUp}><Ranks rows={m.ranking.slice(0,6).map(x=>({label:x.name,value:x.net,detail:`${x.rate}% تحصيل`}))} currency/></Panel>}{shown("forecast")&&<Panel title="توقع التحصيل" sub="وفق سجل السداد السابق" icon={BarChart3}><Big value={formatCurrency(m.open*m.probability/100)} label={`من ${formatCurrency(m.open)} مفتوحة · احتمال ${m.probability}%`}/></Panel>}</Grid>}
 {tab==="portfolio"&&<Grid>{shown("expiry")&&<Panel title="خريطة انتهاء العقود" sub="الأشهر الستة المقبلة" icon={CalendarClock}><div className="grid grid-cols-3 gap-2 sm:grid-cols-6">{m.expiry.map(x=><div key={x.label} className={cn("rounded-md border border-border p-3 text-center",x.count>=5?"bg-destructive/20":x.count>=2?"bg-warning/20":"bg-muted/50")}><b className="block text-xl">{x.count}</b><small>{x.label}</small></div>)}</div></Panel>}{shown("occupancy")&&<Panel title="اتجاه الإشغال" sub="مستنتج من تواريخ العقود" icon={Building2}><Trend data={m.occupancy}/></Panel>}{shown("vacancy")&&<Panel title="متوسط أيام الشغور" sub="بين عقدين متتاليين" icon={Clock3}><Big value={`${m.vacancy} يومًا`} label="للوحدات ذات السجل المتتابع"/></Panel>}{shown("ranking")&&<Panel title="ترتيب العقارات" sub="حسب صافي الدخل" icon={TrendingUp}><Ranks rows={m.ranking.slice(0,7).map(x=>({label:x.name,value:x.net,detail:`${x.contracts} عقد · ${x.rate}%`}))} currency/></Panel>}{shown("geo")&&<Panel title="التوزيع الجغرافي" sub="حسب المدينة والحي" icon={MapPinned}><Bars data={m.geo.slice(0,8)} x="label" series={[['value','عقار','var(--color-primary)']]}/></Panel>}</Grid>}
 {tab==="crm"&&<Grid>{shown("pipeline")&&<Panel title="مسار الفرص" sub="من الاهتمام إلى النجاح" icon={TrendingUp}><Bars data={m.pipeline} x="label" series={[['count','فرصة','var(--color-primary)']]}/></Panel>}{shown("sources")&&<Panel title="مصادر العملاء" sub="القيمة المتوقعة لكل مصدر" icon={Users}><Ranks rows={m.sources.slice(0,7).map(x=>({label:x.label,value:x.value,detail:`${x.count} فرصة`}))} currency/></Panel>}{shown("response")&&<Panel title="سرعة الاستجابة" sub="من الطلب إلى أول تحديث" icon={Clock3}><Big value={`${m.response} ساعة`} label="متوسط طلبات العرض والتوفير"/></Panel>}{shown("team")&&<Panel title="أداء الفريق" sub="إنجاز المهام وسرعة البدء" icon={Users}><Ranks rows={m.team.slice(0,7).map(x=>({label:x.name,value:x.rate,detail:`${x.done}/${x.total} · بدء ${x.hours}س`}))} suffix="%"/></Panel>}</Grid>}
 {tab==="operations"&&<Grid>{shown("risk")&&<Panel title="مخاطر العقود" sub="التأخر والنواقص وقرب الانتهاء" icon={ShieldAlert}><Ranks rows={m.risks.slice(0,8).map(x=>({label:x.label,value:x.score,detail:`${x.overdue} دفعة متأخرة`}))} suffix="/100" danger/></Panel>}{shown("retention")&&<Panel title="الاحتفاظ بالمستأجرين" sub="العقود المرتبطة بتجديد سابق" icon={Users}><Big value={`${m.retention}%`} label="من المستأجرين المسجلين"/></Panel>}{shown("maintenance")&&<Panel title="لوحة الصيانة" sub="التكلفة والمهام المفتوحة" icon={Wrench}><div className="grid grid-cols-2 gap-3"><Big value={formatCurrency(sum(m.maintenanceExpenses.map(x=>x.amount)))} label="تكلفة الصيانة"/><Big value={String(m.maintenanceTasks.filter(x=>!["approved","completed"].includes(x.status)).length)} label="مهام مفتوحة"/></div><Ranks rows={m.maintenance.slice(0,5).map(x=>({label:x.label,value:x.value,detail:"مصروفات صيانة"}))} currency/></Panel>}</Grid>}
 {tab==="smart"&&<Grid>{shown("comparison")&&<Panel title="مقارنة الفترات" sub="هذا الشهر مقابل السابق" icon={BarChart3}><div className="grid grid-cols-3 gap-2"><Compare label="التحصيل" a={m.current.paid} b={m.previous.paid} currency/><Compare label="المصروفات" a={m.current.costs} b={m.previous.costs} currency inverse/><Compare label="العقود" a={m.current.contracts} b={m.previous.contracts}/></div></Panel>}{shown("simulator")&&<Panel title="محاكي السيناريوهات" sub="أثر تغير الإيجار والإشغال والمصروفات" icon={TrendingUp}><Slider label="الإيجار" value={rent} set={setRent}/><Slider label="الإشغال" value={occupancy} set={setOccupancy}/><Slider label="المصروفات" value={costs} set={setCosts}/><Big value={formatCurrency(projected)} label={`${change(projected,currentNet)}% عن الوضع الحالي`}/></Panel>}{shown("summary")&&<Panel title="الموجز التنفيذي" sub="أهم الإشارات اليوم" icon={BrainCircuit} className="lg:col-span-2"><Summary m={m}/></Panel>}</Grid>}
 </section>
}

function Grid({children}:{children:ReactNode}){return <div className="grid gap-4 lg:grid-cols-2">{children}</div>}
function Panel({title,sub,icon:Icon,children,className}:{title:string;sub:string;icon:typeof BarChart3;children:ReactNode;className?:string}){return <section className={cn("surface-card min-w-0 p-5",className)}><header className="mb-4 flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-md border border-border bg-muted text-primary"><Icon className="size-4"/></span><div><h3 className="text-sm font-bold">{title}</h3><p className="text-xs text-muted-foreground">{sub}</p></div></header>{children}</section>}
function Bars({data,x,series,currency}:{data:Record<string,unknown>[];x:string;series:[string,string,string][];currency?:boolean}){return <div className="h-64" dir="ltr"><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey={x} fontSize={10}/><YAxis fontSize={10}/><Tooltip formatter={v=>currency?formatCurrency(Number(v)):Number(v).toLocaleString("ar-SA")}/>{series.map(s=><Bar key={s[0]} dataKey={s[0]} name={s[1]} fill={s[2]} radius={[4,4,0,0]}/>)}</BarChart></ResponsiveContainer></div>}
function Trend({data}:{data:{label:string;value:number}[]}){return <div className="h-64" dir="ltr"><ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" fontSize={10}/><YAxis domain={[0,100]} fontSize={10}/><Tooltip formatter={v=>`${v}%`}/><Line dataKey="value" name="الإشغال" stroke="var(--color-primary)" strokeWidth={3}/></LineChart></ResponsiveContainer></div>}
function Big({value,label}:{value:string;label:string}){return <div className="rounded-md border border-border bg-muted/40 p-5 text-center"><b className="text-2xl">{value}</b><p className="mt-2 text-xs text-muted-foreground">{label}</p></div>}
function Ranks({rows,currency,suffix,danger}:{rows:{label:string;value:number;detail:string}[];currency?:boolean;suffix?:string;danger?:boolean}){return <div className="divide-y divide-border">{rows.length?rows.map((r,i)=><div key={`${r.label}-${i}`} className="flex items-center justify-between gap-3 py-2.5"><div className="min-w-0"><b className="block truncate text-xs">{i+1}. {r.label}</b><small className="text-muted-foreground">{r.detail}</small></div><b className={cn("shrink-0 text-xs",danger&&r.value>=60&&"text-destructive")}>{currency?formatCurrency(r.value):`${r.value}${suffix||""}`}</b></div>):<p className="py-8 text-center text-xs text-muted-foreground">لا توجد بيانات كافية بعد.</p>}</div>}
function Compare({label,a,b,currency,inverse}:{label:string;a:number;b:number;currency?:boolean;inverse?:boolean}){const c=change(a,b),good=inverse?c<=0:c>=0;return <div className="rounded-md border border-border p-3 text-center"><small>{label}</small><b className="block text-xs">{currency?formatCurrency(a):a}</b><span className={good?"text-success":"text-destructive"}>{c>=0?"+":""}{c}%</span></div>}
function Slider({label,value,set}:{label:string;value:number;set:(n:number)=>void}){return <label className="mb-3 block text-xs"><span className="flex justify-between"><span>{label}</span><b>{value>0?"+":""}{value}%</b></span><input type="range" min="-30" max="30" value={value} onChange={e=>set(Number(e.target.value))} className="w-full accent-primary"/></label>}
function Summary({m}:{m:InsightMetrics}){const lines=[`التحصيل المتوقع ${formatCurrency(m.open*m.probability/100)} وفق معدل تاريخي ${m.probability}%.`,m.risks[0]?`أعلى عقد مخاطرة ${m.risks[0].label} بدرجة ${m.risks[0].score}/100.`:"لا توجد مخاطر عقود بارزة.",m.ranking[0]?`أفضل عقار ${m.ranking[0].name} بصافي ${formatCurrency(m.ranking[0].net)}.`:"لا توجد بيانات كافية لترتيب العقارات.",`متوسط الاستجابة ${m.response} ساعة، والاحتفاظ بالمستأجرين ${m.retention}%.`];return <ul className="grid gap-3 sm:grid-cols-2">{lines.map((x,i)=><li key={x} className="rounded-md border border-border bg-muted/30 p-4 text-xs leading-6"><b className="me-2 text-primary">{i+1}.</b>{x}</li>)}</ul>}
