/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompanyProfileRouteImport } from './routes/company-profile'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as MaintenanceRequestRouteImport } from './routes/maintenance-request'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RentRouteImport } from './routes/rent'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SysX9k2ControlRouteImport } from './routes/sys-x9k2-control'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedActivityLogRouteImport } from './routes/_authenticated/activity-log'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedBuildingsRouteImport } from './routes/_authenticated/buildings'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmployeeFormRouteImport } from './routes/_authenticated/employee-form'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedErrorLogRouteImport } from './routes/_authenticated/error-log'
import { Route as AuthenticatedInvoiceFormRouteImport } from './routes/_authenticated/invoice-form'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOwnerFormRouteImport } from './routes/_authenticated/owner-form'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated/partners'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedPropertyFormRouteImport } from './routes/_authenticated/property-form'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedRenewalsRouteImport } from './routes/_authenticated/renewals'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedReserveRouteImport } from './routes/_authenticated/reserve'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedServicePartnersRouteImport } from './routes/_authenticated/service-partners'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTaskFormRouteImport } from './routes/_authenticated/task-form'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTeamChatRouteImport } from './routes/_authenticated/team-chat'
import { Route as AuthenticatedWhatsappLinkRouteImport } from './routes/_authenticated/whatsapp-link'
import { Route as BuildingsCodeRouteImport } from './routes/buildings.$code'
import { Route as OwnerReportTokenRouteImport } from './routes/owner-report.$token'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalCareRouteImport } from './routes/portal.care'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalFinanceRouteImport } from './routes/portal.finance'
import { Route as PortalInsightsRouteImport } from './routes/portal.insights'
import { Route as PortalMaintenanceRouteImport } from './routes/portal.maintenance'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalServicesRouteImport } from './routes/portal.services'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalUnitsRouteImport } from './routes/portal.units'
import { Route as PropertiesCodeRouteImport } from './routes/properties.$code'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts.index'
import { Route as AuthenticatedContractsContractIdRouteImport } from './routes/_authenticated/contracts.$contractId'
import { Route as AuthenticatedGoalsIndexRouteImport } from './routes/_authenticated/goals.index'
import { Route as AuthenticatedGoalsEmployeeIdRouteImport } from './routes/_authenticated/goals.$employeeId'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices.$invoiceId'
import { Route as AuthenticatedListingRequestsIndexRouteImport } from './routes/_authenticated/listing-requests.index'
import { Route as AuthenticatedListingRequestsRequestIdRouteImport } from './routes/_authenticated/listing-requests.$requestId'
import { Route as AuthenticatedMarketingMarketerIdRouteImport } from './routes/_authenticated/marketing.$marketerId'
import { Route as AuthenticatedOwnerSectionSectionIdRouteImport } from './routes/_authenticated/owner-section.$sectionId'
import { Route as AuthenticatedOwnersIndexRouteImport } from './routes/_authenticated/owners.index'
import { Route as AuthenticatedOwnersOwnerIdRouteImport } from './routes/_authenticated/owners.$ownerId'
import { Route as AuthenticatedPaymentReminderPaymentIdRouteImport } from './routes/_authenticated/payment-reminder.$paymentId'
import { Route as AuthenticatedSupplyRequestsIndexRouteImport } from './routes/_authenticated/supply-requests.index'
import { Route as AuthenticatedSupplyRequestsRequestIdRouteImport } from './routes/_authenticated/supply-requests.$requestId'
import { Route as ApiPublicN8nRouteImport } from './routes/api/public/n8n'
import { Route as PortalContractsIndexRouteImport } from './routes/portal.contracts.index'
import { Route as PortalContractsContractIdRouteImport } from './routes/portal.contracts.$contractId'
import { Route as PortalInvoicesIndexRouteImport } from './routes/portal.invoices.index'
import { Route as PortalInvoicesInvoiceIdRouteImport } from './routes/portal.invoices.$invoiceId'
import { Route as ApiPublicFilesSplatRouteImport } from './routes/api/public/files/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyProfileRoute = CompanyProfileRouteImport.update({
  id: '/company-profile',
  path: '/company-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRequestRoute = MaintenanceRequestRouteImport.update({
  id: '/maintenance-request',
  path: '/maintenance-request',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SysX9k2ControlRoute = SysX9k2ControlRouteImport.update({
  id: '/sys-x9k2-control',
  path: '/sys-x9k2-control',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityLogRoute =
  AuthenticatedActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuildingsRoute = AuthenticatedBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeeFormRoute =
  AuthenticatedEmployeeFormRouteImport.update({
    id: '/employee-form',
    path: '/employee-form',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorLogRoute = AuthenticatedErrorLogRouteImport.update({
  id: '/error-log',
  path: '/error-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoiceFormRoute =
  AuthenticatedInvoiceFormRouteImport.update({
    id: '/invoice-form',
    path: '/invoice-form',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnerFormRoute = AuthenticatedOwnerFormRouteImport.update({
  id: '/owner-form',
  path: '/owner-form',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertyFormRoute =
  AuthenticatedPropertyFormRouteImport.update({
    id: '/property-form',
    path: '/property-form',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRenewalsRoute = AuthenticatedRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReserveRoute = AuthenticatedReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicePartnersRoute =
  AuthenticatedServicePartnersRouteImport.update({
    id: '/service-partners',
    path: '/service-partners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaskFormRoute = AuthenticatedTaskFormRouteImport.update({
  id: '/task-form',
  path: '/task-form',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamChatRoute = AuthenticatedTeamChatRouteImport.update({
  id: '/team-chat',
  path: '/team-chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappLinkRoute =
  AuthenticatedWhatsappLinkRouteImport.update({
    id: '/whatsapp-link',
    path: '/whatsapp-link',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BuildingsCodeRoute = BuildingsCodeRouteImport.update({
  id: '/buildings/$code',
  path: '/buildings/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerReportTokenRoute = OwnerReportTokenRouteImport.update({
  id: '/owner-report/$token',
  path: '/owner-report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCareRoute = PortalCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFinanceRoute = PortalFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInsightsRoute = PortalInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMaintenanceRoute = PortalMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalServicesRoute = PortalServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalUnitsRoute = PortalUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => PortalRoute,
} as any)
const PropertiesCodeRoute = PropertiesCodeRouteImport.update({
  id: '/properties/$code',
  path: '/properties/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsContractIdRoute =
  AuthenticatedContractsContractIdRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoalsIndexRoute = AuthenticatedGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsEmployeeIdRoute =
  AuthenticatedGoalsEmployeeIdRouteImport.update({
    id: '/goals/$employeeId',
    path: '/goals/$employeeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingRequestsIndexRoute =
  AuthenticatedListingRequestsIndexRouteImport.update({
    id: '/listing-requests/',
    path: '/listing-requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingRequestsRequestIdRoute =
  AuthenticatedListingRequestsRequestIdRouteImport.update({
    id: '/listing-requests/$requestId',
    path: '/listing-requests/$requestId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingMarketerIdRoute =
  AuthenticatedMarketingMarketerIdRouteImport.update({
    id: '/$marketerId',
    path: '/$marketerId',
    getParentRoute: () => AuthenticatedMarketingRoute,
  } as any)
const AuthenticatedOwnerSectionSectionIdRoute =
  AuthenticatedOwnerSectionSectionIdRouteImport.update({
    id: '/owner-section/$sectionId',
    path: '/owner-section/$sectionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnersIndexRoute =
  AuthenticatedOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnersOwnerIdRoute =
  AuthenticatedOwnersOwnerIdRouteImport.update({
    id: '/owners/$ownerId',
    path: '/owners/$ownerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentReminderPaymentIdRoute =
  AuthenticatedPaymentReminderPaymentIdRouteImport.update({
    id: '/payment-reminder/$paymentId',
    path: '/payment-reminder/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplyRequestsIndexRoute =
  AuthenticatedSupplyRequestsIndexRouteImport.update({
    id: '/supply-requests/',
    path: '/supply-requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplyRequestsRequestIdRoute =
  AuthenticatedSupplyRequestsRequestIdRouteImport.update({
    id: '/supply-requests/$requestId',
    path: '/supply-requests/$requestId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicN8nRoute = ApiPublicN8nRouteImport.update({
  id: '/api/public/n8n',
  path: '/api/public/n8n',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalContractsIndexRoute = PortalContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContractsContractIdRoute =
  PortalContractsContractIdRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalInvoicesIndexRoute = PortalInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInvoicesInvoiceIdRoute = PortalInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => PortalRoute,
} as any)
const ApiPublicFilesSplatRoute = ApiPublicFilesSplatRouteImport.update({
  id: '/api/public/files/$',
  path: '/api/public/files/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/list-property': typeof ListPropertyRoute
  '/maintenance-request': typeof MaintenanceRequestRoute
  '/partner': typeof PartnerRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/rent': typeof RentRoute
  '/sale': typeof SaleRoute
  '/showcase': typeof ShowcaseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sys-x9k2-control': typeof SysX9k2ControlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/ai': typeof AuthenticatedAiRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/buildings': typeof AuthenticatedBuildingsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employee-form': typeof AuthenticatedEmployeeFormRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/error-log': typeof AuthenticatedErrorLogRoute
  '/invoice-form': typeof AuthenticatedInvoiceFormRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/owner-form': typeof AuthenticatedOwnerFormRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/property-form': typeof AuthenticatedPropertyFormRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/reserve': typeof AuthenticatedReserveRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/service-partners': typeof AuthenticatedServicePartnersRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/task-form': typeof AuthenticatedTaskFormRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team-chat': typeof AuthenticatedTeamChatRoute
  '/whatsapp-link': typeof AuthenticatedWhatsappLinkRoute
  '/buildings/$code': typeof BuildingsCodeRoute
  '/owner-report/$token': typeof OwnerReportTokenRoute
  '/portal/care': typeof PortalCareRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/finance': typeof PortalFinanceRoute
  '/portal/insights': typeof PortalInsightsRoute
  '/portal/maintenance': typeof PortalMaintenanceRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/services': typeof PortalServicesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/units': typeof PortalUnitsRoute
  '/properties/$code': typeof PropertiesCodeRoute
  '/partner/': typeof PartnerIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/contracts/$contractId': typeof AuthenticatedContractsContractIdRoute
  '/goals/$employeeId': typeof AuthenticatedGoalsEmployeeIdRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/listing-requests/$requestId': typeof AuthenticatedListingRequestsRequestIdRoute
  '/marketing/$marketerId': typeof AuthenticatedMarketingMarketerIdRoute
  '/owner-section/$sectionId': typeof AuthenticatedOwnerSectionSectionIdRoute
  '/owners/$ownerId': typeof AuthenticatedOwnersOwnerIdRoute
  '/payment-reminder/$paymentId': typeof AuthenticatedPaymentReminderPaymentIdRoute
  '/supply-requests/$requestId': typeof AuthenticatedSupplyRequestsRequestIdRoute
  '/api/public/n8n': typeof ApiPublicN8nRoute
  '/portal/contracts/$contractId': typeof PortalContractsContractIdRoute
  '/portal/invoices/$invoiceId': typeof PortalInvoicesInvoiceIdRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/goals/': typeof AuthenticatedGoalsIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/listing-requests/': typeof AuthenticatedListingRequestsIndexRoute
  '/owners/': typeof AuthenticatedOwnersIndexRoute
  '/supply-requests/': typeof AuthenticatedSupplyRequestsIndexRoute
  '/portal/contracts/': typeof PortalContractsIndexRoute
  '/portal/invoices/': typeof PortalInvoicesIndexRoute
  '/api/public/files/$': typeof ApiPublicFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/list-property': typeof ListPropertyRoute
  '/maintenance-request': typeof MaintenanceRequestRoute
  '/privacy': typeof PrivacyRoute
  '/rent': typeof RentRoute
  '/sale': typeof SaleRoute
  '/showcase': typeof ShowcaseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sys-x9k2-control': typeof SysX9k2ControlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/ai': typeof AuthenticatedAiRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/buildings': typeof AuthenticatedBuildingsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employee-form': typeof AuthenticatedEmployeeFormRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/error-log': typeof AuthenticatedErrorLogRoute
  '/invoice-form': typeof AuthenticatedInvoiceFormRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/owner-form': typeof AuthenticatedOwnerFormRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/property-form': typeof AuthenticatedPropertyFormRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/reserve': typeof AuthenticatedReserveRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/service-partners': typeof AuthenticatedServicePartnersRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/task-form': typeof AuthenticatedTaskFormRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team-chat': typeof AuthenticatedTeamChatRoute
  '/whatsapp-link': typeof AuthenticatedWhatsappLinkRoute
  '/buildings/$code': typeof BuildingsCodeRoute
  '/owner-report/$token': typeof OwnerReportTokenRoute
  '/portal/care': typeof PortalCareRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/finance': typeof PortalFinanceRoute
  '/portal/insights': typeof PortalInsightsRoute
  '/portal/maintenance': typeof PortalMaintenanceRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/services': typeof PortalServicesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/units': typeof PortalUnitsRoute
  '/properties/$code': typeof PropertiesCodeRoute
  '/partner': typeof PartnerIndexRoute
  '/portal': typeof PortalIndexRoute
  '/contracts/$contractId': typeof AuthenticatedContractsContractIdRoute
  '/goals/$employeeId': typeof AuthenticatedGoalsEmployeeIdRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/listing-requests/$requestId': typeof AuthenticatedListingRequestsRequestIdRoute
  '/marketing/$marketerId': typeof AuthenticatedMarketingMarketerIdRoute
  '/owner-section/$sectionId': typeof AuthenticatedOwnerSectionSectionIdRoute
  '/owners/$ownerId': typeof AuthenticatedOwnersOwnerIdRoute
  '/payment-reminder/$paymentId': typeof AuthenticatedPaymentReminderPaymentIdRoute
  '/supply-requests/$requestId': typeof AuthenticatedSupplyRequestsRequestIdRoute
  '/api/public/n8n': typeof ApiPublicN8nRoute
  '/portal/contracts/$contractId': typeof PortalContractsContractIdRoute
  '/portal/invoices/$invoiceId': typeof PortalInvoicesInvoiceIdRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/goals': typeof AuthenticatedGoalsIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/listing-requests': typeof AuthenticatedListingRequestsIndexRoute
  '/owners': typeof AuthenticatedOwnersIndexRoute
  '/supply-requests': typeof AuthenticatedSupplyRequestsIndexRoute
  '/portal/contracts': typeof PortalContractsIndexRoute
  '/portal/invoices': typeof PortalInvoicesIndexRoute
  '/api/public/files/$': typeof ApiPublicFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/company-profile': typeof CompanyProfileRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/list-property': typeof ListPropertyRoute
  '/maintenance-request': typeof MaintenanceRequestRoute
  '/partner': typeof PartnerRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/rent': typeof RentRoute
  '/sale': typeof SaleRoute
  '/showcase': typeof ShowcaseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sys-x9k2-control': typeof SysX9k2ControlRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/activity-log': typeof AuthenticatedActivityLogRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/buildings': typeof AuthenticatedBuildingsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employee-form': typeof AuthenticatedEmployeeFormRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/error-log': typeof AuthenticatedErrorLogRoute
  '/_authenticated/invoice-form': typeof AuthenticatedInvoiceFormRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/owner-form': typeof AuthenticatedOwnerFormRoute
  '/_authenticated/partners': typeof AuthenticatedPartnersRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/property-form': typeof AuthenticatedPropertyFormRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/renewals': typeof AuthenticatedRenewalsRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_authenticated/reserve': typeof AuthenticatedReserveRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/service-partners': typeof AuthenticatedServicePartnersRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/task-form': typeof AuthenticatedTaskFormRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team-chat': typeof AuthenticatedTeamChatRoute
  '/_authenticated/whatsapp-link': typeof AuthenticatedWhatsappLinkRoute
  '/buildings/$code': typeof BuildingsCodeRoute
  '/owner-report/$token': typeof OwnerReportTokenRoute
  '/portal/care': typeof PortalCareRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/finance': typeof PortalFinanceRoute
  '/portal/insights': typeof PortalInsightsRoute
  '/portal/maintenance': typeof PortalMaintenanceRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/services': typeof PortalServicesRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/units': typeof PortalUnitsRoute
  '/properties/$code': typeof PropertiesCodeRoute
  '/partner/': typeof PartnerIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/contracts/$contractId': typeof AuthenticatedContractsContractIdRoute
  '/_authenticated/goals/$employeeId': typeof AuthenticatedGoalsEmployeeIdRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/listing-requests/$requestId': typeof AuthenticatedListingRequestsRequestIdRoute
  '/_authenticated/marketing/$marketerId': typeof AuthenticatedMarketingMarketerIdRoute
  '/_authenticated/owner-section/$sectionId': typeof AuthenticatedOwnerSectionSectionIdRoute
  '/_authenticated/owners/$ownerId': typeof AuthenticatedOwnersOwnerIdRoute
  '/_authenticated/payment-reminder/$paymentId': typeof AuthenticatedPaymentReminderPaymentIdRoute
  '/_authenticated/supply-requests/$requestId': typeof AuthenticatedSupplyRequestsRequestIdRoute
  '/api/public/n8n': typeof ApiPublicN8nRoute
  '/portal/contracts/$contractId': typeof PortalContractsContractIdRoute
  '/portal/invoices/$invoiceId': typeof PortalInvoicesInvoiceIdRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/goals/': typeof AuthenticatedGoalsIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/listing-requests/': typeof AuthenticatedListingRequestsIndexRoute
  '/_authenticated/owners/': typeof AuthenticatedOwnersIndexRoute
  '/_authenticated/supply-requests/': typeof AuthenticatedSupplyRequestsIndexRoute
  '/portal/contracts/': typeof PortalContractsIndexRoute
  '/portal/invoices/': typeof PortalInvoicesIndexRoute
  '/api/public/files/$': typeof ApiPublicFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/company-profile'
    | '/contact'
    | '/favorites'
    | '/list-property'
    | '/maintenance-request'
    | '/partner'
    | '/portal'
    | '/privacy'
    | '/rent'
    | '/sale'
    | '/showcase'
    | '/sitemap.xml'
    | '/sys-x9k2-control'
    | '/terms'
    | '/thank-you'
    | '/activities'
    | '/activity-log'
    | '/ai'
    | '/backup'
    | '/buildings'
    | '/clients'
    | '/crm'
    | '/dashboard'
    | '/employee-form'
    | '/employees'
    | '/error-log'
    | '/invoice-form'
    | '/maintenance'
    | '/marketing'
    | '/notifications'
    | '/owner-form'
    | '/partners'
    | '/properties'
    | '/property-form'
    | '/reminders'
    | '/renewals'
    | '/reservations'
    | '/reserve'
    | '/roles'
    | '/service-partners'
    | '/services'
    | '/settings'
    | '/task-form'
    | '/tasks'
    | '/team-chat'
    | '/whatsapp-link'
    | '/buildings/$code'
    | '/owner-report/$token'
    | '/portal/care'
    | '/portal/documents'
    | '/portal/finance'
    | '/portal/insights'
    | '/portal/maintenance'
    | '/portal/messages'
    | '/portal/services'
    | '/portal/settings'
    | '/portal/units'
    | '/properties/$code'
    | '/partner/'
    | '/portal/'
    | '/contracts/$contractId'
    | '/goals/$employeeId'
    | '/invoices/$invoiceId'
    | '/listing-requests/$requestId'
    | '/marketing/$marketerId'
    | '/owner-section/$sectionId'
    | '/owners/$ownerId'
    | '/payment-reminder/$paymentId'
    | '/supply-requests/$requestId'
    | '/api/public/n8n'
    | '/portal/contracts/$contractId'
    | '/portal/invoices/$invoiceId'
    | '/contracts/'
    | '/goals/'
    | '/invoices/'
    | '/listing-requests/'
    | '/owners/'
    | '/supply-requests/'
    | '/portal/contracts/'
    | '/portal/invoices/'
    | '/api/public/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/company-profile'
    | '/contact'
    | '/favorites'
    | '/list-property'
    | '/maintenance-request'
    | '/privacy'
    | '/rent'
    | '/sale'
    | '/showcase'
    | '/sitemap.xml'
    | '/sys-x9k2-control'
    | '/terms'
    | '/thank-you'
    | '/activities'
    | '/activity-log'
    | '/ai'
    | '/backup'
    | '/buildings'
    | '/clients'
    | '/crm'
    | '/dashboard'
    | '/employee-form'
    | '/employees'
    | '/error-log'
    | '/invoice-form'
    | '/maintenance'
    | '/marketing'
    | '/notifications'
    | '/owner-form'
    | '/partners'
    | '/properties'
    | '/property-form'
    | '/reminders'
    | '/renewals'
    | '/reservations'
    | '/reserve'
    | '/roles'
    | '/service-partners'
    | '/services'
    | '/settings'
    | '/task-form'
    | '/tasks'
    | '/team-chat'
    | '/whatsapp-link'
    | '/buildings/$code'
    | '/owner-report/$token'
    | '/portal/care'
    | '/portal/documents'
    | '/portal/finance'
    | '/portal/insights'
    | '/portal/maintenance'
    | '/portal/messages'
    | '/portal/services'
    | '/portal/settings'
    | '/portal/units'
    | '/properties/$code'
    | '/partner'
    | '/portal'
    | '/contracts/$contractId'
    | '/goals/$employeeId'
    | '/invoices/$invoiceId'
    | '/listing-requests/$requestId'
    | '/marketing/$marketerId'
    | '/owner-section/$sectionId'
    | '/owners/$ownerId'
    | '/payment-reminder/$paymentId'
    | '/supply-requests/$requestId'
    | '/api/public/n8n'
    | '/portal/contracts/$contractId'
    | '/portal/invoices/$invoiceId'
    | '/contracts'
    | '/goals'
    | '/invoices'
    | '/listing-requests'
    | '/owners'
    | '/supply-requests'
    | '/portal/contracts'
    | '/portal/invoices'
    | '/api/public/files/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/company-profile'
    | '/contact'
    | '/favorites'
    | '/list-property'
    | '/maintenance-request'
    | '/partner'
    | '/portal'
    | '/privacy'
    | '/rent'
    | '/sale'
    | '/showcase'
    | '/sitemap.xml'
    | '/sys-x9k2-control'
    | '/terms'
    | '/thank-you'
    | '/_authenticated/activities'
    | '/_authenticated/activity-log'
    | '/_authenticated/ai'
    | '/_authenticated/backup'
    | '/_authenticated/buildings'
    | '/_authenticated/clients'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/employee-form'
    | '/_authenticated/employees'
    | '/_authenticated/error-log'
    | '/_authenticated/invoice-form'
    | '/_authenticated/maintenance'
    | '/_authenticated/marketing'
    | '/_authenticated/notifications'
    | '/_authenticated/owner-form'
    | '/_authenticated/partners'
    | '/_authenticated/properties'
    | '/_authenticated/property-form'
    | '/_authenticated/reminders'
    | '/_authenticated/renewals'
    | '/_authenticated/reservations'
    | '/_authenticated/reserve'
    | '/_authenticated/roles'
    | '/_authenticated/service-partners'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/task-form'
    | '/_authenticated/tasks'
    | '/_authenticated/team-chat'
    | '/_authenticated/whatsapp-link'
    | '/buildings/$code'
    | '/owner-report/$token'
    | '/portal/care'
    | '/portal/documents'
    | '/portal/finance'
    | '/portal/insights'
    | '/portal/maintenance'
    | '/portal/messages'
    | '/portal/services'
    | '/portal/settings'
    | '/portal/units'
    | '/properties/$code'
    | '/partner/'
    | '/portal/'
    | '/_authenticated/contracts/$contractId'
    | '/_authenticated/goals/$employeeId'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/listing-requests/$requestId'
    | '/_authenticated/marketing/$marketerId'
    | '/_authenticated/owner-section/$sectionId'
    | '/_authenticated/owners/$ownerId'
    | '/_authenticated/payment-reminder/$paymentId'
    | '/_authenticated/supply-requests/$requestId'
    | '/api/public/n8n'
    | '/portal/contracts/$contractId'
    | '/portal/invoices/$invoiceId'
    | '/_authenticated/contracts/'
    | '/_authenticated/goals/'
    | '/_authenticated/invoices/'
    | '/_authenticated/listing-requests/'
    | '/_authenticated/owners/'
    | '/_authenticated/supply-requests/'
    | '/portal/contracts/'
    | '/portal/invoices/'
    | '/api/public/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CompanyProfileRoute: typeof CompanyProfileRoute
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  ListPropertyRoute: typeof ListPropertyRoute
  MaintenanceRequestRoute: typeof MaintenanceRequestRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RentRoute: typeof RentRoute
  SaleRoute: typeof SaleRoute
  ShowcaseRoute: typeof ShowcaseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SysX9k2ControlRoute: typeof SysX9k2ControlRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  BuildingsCodeRoute: typeof BuildingsCodeRoute
  OwnerReportTokenRoute: typeof OwnerReportTokenRoute
  PropertiesCodeRoute: typeof PropertiesCodeRoute
  ApiPublicN8nRoute: typeof ApiPublicN8nRoute
  ApiPublicFilesSplatRoute: typeof ApiPublicFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-profile': {
      id: '/company-profile'
      path: '/company-profile'
      fullPath: '/company-profile'
      preLoaderRoute: typeof CompanyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance-request': {
      id: '/maintenance-request'
      path: '/maintenance-request'
      fullPath: '/maintenance-request'
      preLoaderRoute: typeof MaintenanceRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sys-x9k2-control': {
      id: '/sys-x9k2-control'
      path: '/sys-x9k2-control'
      fullPath: '/sys-x9k2-control'
      preLoaderRoute: typeof SysX9k2ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity-log': {
      id: '/_authenticated/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof AuthenticatedActivityLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buildings': {
      id: '/_authenticated/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof AuthenticatedBuildingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employee-form': {
      id: '/_authenticated/employee-form'
      path: '/employee-form'
      fullPath: '/employee-form'
      preLoaderRoute: typeof AuthenticatedEmployeeFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/error-log': {
      id: '/_authenticated/error-log'
      path: '/error-log'
      fullPath: '/error-log'
      preLoaderRoute: typeof AuthenticatedErrorLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoice-form': {
      id: '/_authenticated/invoice-form'
      path: '/invoice-form'
      fullPath: '/invoice-form'
      preLoaderRoute: typeof AuthenticatedInvoiceFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner-form': {
      id: '/_authenticated/owner-form'
      path: '/owner-form'
      fullPath: '/owner-form'
      preLoaderRoute: typeof AuthenticatedOwnerFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/property-form': {
      id: '/_authenticated/property-form'
      path: '/property-form'
      fullPath: '/property-form'
      preLoaderRoute: typeof AuthenticatedPropertyFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/renewals': {
      id: '/_authenticated/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AuthenticatedRenewalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reserve': {
      id: '/_authenticated/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof AuthenticatedReserveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service-partners': {
      id: '/_authenticated/service-partners'
      path: '/service-partners'
      fullPath: '/service-partners'
      preLoaderRoute: typeof AuthenticatedServicePartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/task-form': {
      id: '/_authenticated/task-form'
      path: '/task-form'
      fullPath: '/task-form'
      preLoaderRoute: typeof AuthenticatedTaskFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-chat': {
      id: '/_authenticated/team-chat'
      path: '/team-chat'
      fullPath: '/team-chat'
      preLoaderRoute: typeof AuthenticatedTeamChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp-link': {
      id: '/_authenticated/whatsapp-link'
      path: '/whatsapp-link'
      fullPath: '/whatsapp-link'
      preLoaderRoute: typeof AuthenticatedWhatsappLinkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/buildings/$code': {
      id: '/buildings/$code'
      path: '/buildings/$code'
      fullPath: '/buildings/$code'
      preLoaderRoute: typeof BuildingsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-report/$token': {
      id: '/owner-report/$token'
      path: '/owner-report/$token'
      fullPath: '/owner-report/$token'
      preLoaderRoute: typeof OwnerReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/care': {
      id: '/portal/care'
      path: '/care'
      fullPath: '/portal/care'
      preLoaderRoute: typeof PortalCareRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/finance': {
      id: '/portal/finance'
      path: '/finance'
      fullPath: '/portal/finance'
      preLoaderRoute: typeof PortalFinanceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/insights': {
      id: '/portal/insights'
      path: '/insights'
      fullPath: '/portal/insights'
      preLoaderRoute: typeof PortalInsightsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/maintenance': {
      id: '/portal/maintenance'
      path: '/maintenance'
      fullPath: '/portal/maintenance'
      preLoaderRoute: typeof PortalMaintenanceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/services': {
      id: '/portal/services'
      path: '/services'
      fullPath: '/portal/services'
      preLoaderRoute: typeof PortalServicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/units': {
      id: '/portal/units'
      path: '/units'
      fullPath: '/portal/units'
      preLoaderRoute: typeof PortalUnitsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/properties/$code': {
      id: '/properties/$code'
      path: '/properties/$code'
      fullPath: '/properties/$code'
      preLoaderRoute: typeof PropertiesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/$contractId': {
      id: '/_authenticated/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof AuthenticatedContractsContractIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals/': {
      id: '/_authenticated/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AuthenticatedGoalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals/$employeeId': {
      id: '/_authenticated/goals/$employeeId'
      path: '/goals/$employeeId'
      fullPath: '/goals/$employeeId'
      preLoaderRoute: typeof AuthenticatedGoalsEmployeeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listing-requests/': {
      id: '/_authenticated/listing-requests/'
      path: '/listing-requests'
      fullPath: '/listing-requests/'
      preLoaderRoute: typeof AuthenticatedListingRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listing-requests/$requestId': {
      id: '/_authenticated/listing-requests/$requestId'
      path: '/listing-requests/$requestId'
      fullPath: '/listing-requests/$requestId'
      preLoaderRoute: typeof AuthenticatedListingRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing/$marketerId': {
      id: '/_authenticated/marketing/$marketerId'
      path: '/$marketerId'
      fullPath: '/marketing/$marketerId'
      preLoaderRoute: typeof AuthenticatedMarketingMarketerIdRouteImport
      parentRoute: typeof AuthenticatedMarketingRoute
    }
    '/_authenticated/owner-section/$sectionId': {
      id: '/_authenticated/owner-section/$sectionId'
      path: '/owner-section/$sectionId'
      fullPath: '/owner-section/$sectionId'
      preLoaderRoute: typeof AuthenticatedOwnerSectionSectionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owners/': {
      id: '/_authenticated/owners/'
      path: '/owners'
      fullPath: '/owners/'
      preLoaderRoute: typeof AuthenticatedOwnersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owners/$ownerId': {
      id: '/_authenticated/owners/$ownerId'
      path: '/owners/$ownerId'
      fullPath: '/owners/$ownerId'
      preLoaderRoute: typeof AuthenticatedOwnersOwnerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-reminder/$paymentId': {
      id: '/_authenticated/payment-reminder/$paymentId'
      path: '/payment-reminder/$paymentId'
      fullPath: '/payment-reminder/$paymentId'
      preLoaderRoute: typeof AuthenticatedPaymentReminderPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supply-requests/': {
      id: '/_authenticated/supply-requests/'
      path: '/supply-requests'
      fullPath: '/supply-requests/'
      preLoaderRoute: typeof AuthenticatedSupplyRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supply-requests/$requestId': {
      id: '/_authenticated/supply-requests/$requestId'
      path: '/supply-requests/$requestId'
      fullPath: '/supply-requests/$requestId'
      preLoaderRoute: typeof AuthenticatedSupplyRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/n8n': {
      id: '/api/public/n8n'
      path: '/api/public/n8n'
      fullPath: '/api/public/n8n'
      preLoaderRoute: typeof ApiPublicN8nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/contracts/': {
      id: '/portal/contracts/'
      path: '/contracts'
      fullPath: '/portal/contracts/'
      preLoaderRoute: typeof PortalContractsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contracts/$contractId': {
      id: '/portal/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/portal/contracts/$contractId'
      preLoaderRoute: typeof PortalContractsContractIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/invoices/': {
      id: '/portal/invoices/'
      path: '/invoices'
      fullPath: '/portal/invoices/'
      preLoaderRoute: typeof PortalInvoicesIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/invoices/$invoiceId': {
      id: '/portal/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/portal/invoices/$invoiceId'
      preLoaderRoute: typeof PortalInvoicesInvoiceIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/public/files/$': {
      id: '/api/public/files/$'
      path: '/api/public/files/$'
      fullPath: '/api/public/files/$'
      preLoaderRoute: typeof ApiPublicFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMarketingRouteChildren {
  AuthenticatedMarketingMarketerIdRoute: typeof AuthenticatedMarketingMarketerIdRoute
}

const AuthenticatedMarketingRouteChildren: AuthenticatedMarketingRouteChildren =
  {
    AuthenticatedMarketingMarketerIdRoute:
      AuthenticatedMarketingMarketerIdRoute,
  }

const AuthenticatedMarketingRouteWithChildren =
  AuthenticatedMarketingRoute._addFileChildren(
    AuthenticatedMarketingRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedActivityLogRoute: typeof AuthenticatedActivityLogRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedBuildingsRoute: typeof AuthenticatedBuildingsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeeFormRoute: typeof AuthenticatedEmployeeFormRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedErrorLogRoute: typeof AuthenticatedErrorLogRoute
  AuthenticatedInvoiceFormRoute: typeof AuthenticatedInvoiceFormRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOwnerFormRoute: typeof AuthenticatedOwnerFormRoute
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedPropertyFormRoute: typeof AuthenticatedPropertyFormRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedRenewalsRoute: typeof AuthenticatedRenewalsRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedReserveRoute: typeof AuthenticatedReserveRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedServicePartnersRoute: typeof AuthenticatedServicePartnersRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTaskFormRoute: typeof AuthenticatedTaskFormRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamChatRoute: typeof AuthenticatedTeamChatRoute
  AuthenticatedWhatsappLinkRoute: typeof AuthenticatedWhatsappLinkRoute
  AuthenticatedContractsContractIdRoute: typeof AuthenticatedContractsContractIdRoute
  AuthenticatedGoalsEmployeeIdRoute: typeof AuthenticatedGoalsEmployeeIdRoute
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
  AuthenticatedListingRequestsRequestIdRoute: typeof AuthenticatedListingRequestsRequestIdRoute
  AuthenticatedOwnerSectionSectionIdRoute: typeof AuthenticatedOwnerSectionSectionIdRoute
  AuthenticatedOwnersOwnerIdRoute: typeof AuthenticatedOwnersOwnerIdRoute
  AuthenticatedPaymentReminderPaymentIdRoute: typeof AuthenticatedPaymentReminderPaymentIdRoute
  AuthenticatedSupplyRequestsRequestIdRoute: typeof AuthenticatedSupplyRequestsRequestIdRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedGoalsIndexRoute: typeof AuthenticatedGoalsIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedListingRequestsIndexRoute: typeof AuthenticatedListingRequestsIndexRoute
  AuthenticatedOwnersIndexRoute: typeof AuthenticatedOwnersIndexRoute
  AuthenticatedSupplyRequestsIndexRoute: typeof AuthenticatedSupplyRequestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedActivityLogRoute: AuthenticatedActivityLogRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedBuildingsRoute: AuthenticatedBuildingsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeeFormRoute: AuthenticatedEmployeeFormRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedErrorLogRoute: AuthenticatedErrorLogRoute,
  AuthenticatedInvoiceFormRoute: AuthenticatedInvoiceFormRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOwnerFormRoute: AuthenticatedOwnerFormRoute,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedPropertyFormRoute: AuthenticatedPropertyFormRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedRenewalsRoute: AuthenticatedRenewalsRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedReserveRoute: AuthenticatedReserveRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedServicePartnersRoute: AuthenticatedServicePartnersRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTaskFormRoute: AuthenticatedTaskFormRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamChatRoute: AuthenticatedTeamChatRoute,
  AuthenticatedWhatsappLinkRoute: AuthenticatedWhatsappLinkRoute,
  AuthenticatedContractsContractIdRoute: AuthenticatedContractsContractIdRoute,
  AuthenticatedGoalsEmployeeIdRoute: AuthenticatedGoalsEmployeeIdRoute,
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
  AuthenticatedListingRequestsRequestIdRoute:
    AuthenticatedListingRequestsRequestIdRoute,
  AuthenticatedOwnerSectionSectionIdRoute:
    AuthenticatedOwnerSectionSectionIdRoute,
  AuthenticatedOwnersOwnerIdRoute: AuthenticatedOwnersOwnerIdRoute,
  AuthenticatedPaymentReminderPaymentIdRoute:
    AuthenticatedPaymentReminderPaymentIdRoute,
  AuthenticatedSupplyRequestsRequestIdRoute:
    AuthenticatedSupplyRequestsRequestIdRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedGoalsIndexRoute: AuthenticatedGoalsIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedListingRequestsIndexRoute:
    AuthenticatedListingRequestsIndexRoute,
  AuthenticatedOwnersIndexRoute: AuthenticatedOwnersIndexRoute,
  AuthenticatedSupplyRequestsIndexRoute: AuthenticatedSupplyRequestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PartnerRouteChildren {
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

interface PortalRouteChildren {
  PortalCareRoute: typeof PortalCareRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalFinanceRoute: typeof PortalFinanceRoute
  PortalInsightsRoute: typeof PortalInsightsRoute
  PortalMaintenanceRoute: typeof PortalMaintenanceRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalServicesRoute: typeof PortalServicesRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalUnitsRoute: typeof PortalUnitsRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalContractsContractIdRoute: typeof PortalContractsContractIdRoute
  PortalInvoicesInvoiceIdRoute: typeof PortalInvoicesInvoiceIdRoute
  PortalContractsIndexRoute: typeof PortalContractsIndexRoute
  PortalInvoicesIndexRoute: typeof PortalInvoicesIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCareRoute: PortalCareRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalFinanceRoute: PortalFinanceRoute,
  PortalInsightsRoute: PortalInsightsRoute,
  PortalMaintenanceRoute: PortalMaintenanceRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalServicesRoute: PortalServicesRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalUnitsRoute: PortalUnitsRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalContractsContractIdRoute: PortalContractsContractIdRoute,
  PortalInvoicesInvoiceIdRoute: PortalInvoicesInvoiceIdRoute,
  PortalContractsIndexRoute: PortalContractsIndexRoute,
  PortalInvoicesIndexRoute: PortalInvoicesIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CompanyProfileRoute: CompanyProfileRoute,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  ListPropertyRoute: ListPropertyRoute,
  MaintenanceRequestRoute: MaintenanceRequestRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RentRoute: RentRoute,
  SaleRoute: SaleRoute,
  ShowcaseRoute: ShowcaseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SysX9k2ControlRoute: SysX9k2ControlRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  BuildingsCodeRoute: BuildingsCodeRoute,
  OwnerReportTokenRoute: OwnerReportTokenRoute,
  PropertiesCodeRoute: PropertiesCodeRoute,
  ApiPublicN8nRoute: ApiPublicN8nRoute,
  ApiPublicFilesSplatRoute: ApiPublicFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
